# Generated by Django 5.1 on 2024-08-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('driver', 'Driver')], default='staff', max_length=10),
        ),
    ]
