# Generated by Django 5.0.7 on 2024-08-25 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_mess_discount_amount_mess_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='initial_transaction_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 9, 39, 23, 884178, tzinfo=datetime.timezone.utc)),
        ),
    ]
