# Generated by Django 5.0.7 on 2024-08-25 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_transaction_initial_transaction_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='initial_transaction_created',
        ),
        migrations.AddField(
            model_name='mess',
            name='initial_transaction_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 9, 42, 49, 333601, tzinfo=datetime.timezone.utc)),
        ),
    ]
