# Generated by Django 5.1 on 2024-08-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
