# Generated by Django 5.1 on 2024-08-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_order_delivery_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passcode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
