# Generated by Django 5.1 on 2024-08-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_floor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(default=4),
            preserve_default=False,
        ),
    ]
