# Generated by Django 5.1 on 2024-08-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_user_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='bank_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mess',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='bank_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='messtype',
            name='name',
            field=models.CharField(choices=[('breakfast_lunch_dinner', 'Breakfast and Lunch and Dinner'), ('breakfast_lunch', 'Breakfast and Lunch'), ('breakfast_dinner', 'Breakfast and Dinner'), ('lunch_dinner', 'Lunch and Dinner')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cash-bank', 'Cash and Bank')], default='cash', max_length=20),
        ),
    ]
