# Generated by Django 5.1 on 2024-08-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('takeaway', 'Takeaway'), ('dining', 'Dining'), ('delivery', 'Delivery')], default='dining', max_length=20),
        ),
    ]
