# Generated by Django 5.1 on 2024-08-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0006_mess_bank_amount_mess_cash_amount_order_bank_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('staff', 'Staff'), ('driver', 'Driver')], max_length=10, null=True),
        ),
    ]
