# Generated by Django 5.1 on 2024-08-17 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('day_of_week', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9, null=True)),
                ('meal_type', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default='admin', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('combo', 'Combo'), ('breakfast_lunch', 'Breakfast and Lunch'), ('breakfast_dinner', 'Breakfast and Dinner'), ('lunch_dinner', 'Lunch and Dinner')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.dish')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='restaurant_app.menu')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='mess_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurant_app.messtype'),
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('mess_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messes', to='restaurant_app.messtype')),
            ],
            options={
                'unique_together': {('mess_type', 'customer_name')},
            },
        ),
    ]
