# Generated by Django 5.1 on 2024-08-24 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0008_credituser_alter_order_payment_method_creditorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditorder',
            options={'ordering': ('credit_user', 'order__created_at')},
        ),
        migrations.AlterModelOptions(
            name='credituser',
            options={'ordering': ('last_payment_date',)},
        ),
    ]
