# Generated by Django 5.1 on 2024-08-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0009_menu_messtype_menuitem_menu_mess_type_mess'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='selected_menus',
            field=models.ManyToManyField(related_name='selected_messes', to='restaurant_app.menu'),
        ),
    ]
