# Generated by Django 5.1 on 2024-08-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0009_alter_creditorder_options_alter_credituser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
