# Generated by Django 5.1 on 2024-08-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_mess_selected_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=20, null=True),
        ),
    ]
