# Generated by Django 5.1 on 2024-08-24 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_order_credit_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='credituser',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
