# Generated by Django 5.1 on 2024-08-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_remove_menu_meal_type_menuitem_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mess',
            name='selected_menus',
        ),
        migrations.AddField(
            model_name='mess',
            name='menus',
            field=models.ManyToManyField(related_name='messes', to='restaurant_app.menu'),
        ),
    ]
