# Generated by Django 5.1 on 2024-08-24 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0011_credituser_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
    ]
