# Generated by Django 5.1 on 2024-08-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0012_remove_mess_selected_menus_mess_menus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mess',
            name='padi_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mess',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mess',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('cash-bank', 'Cash and Bank')], default='cash', max_length=20),
        ),
    ]
