# Generated by Django 5.1 on 2024-08-25 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_alter_credituser_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 24, 9, 9, 1, 736971, tzinfo=datetime.timezone.utc)),
        ),
    ]
