# Generated by Django 5.1 on 2024-08-24 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_alter_credituser_time_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 23, 14, 22, 31, 226241, tzinfo=datetime.timezone.utc)),
        ),
    ]
