# Generated by Django 5.1 on 2024-08-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0013_mess_padi_amount_mess_pending_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mess',
            old_name='padi_amount',
            new_name='paid_amount',
        ),
    ]
