# Generated by Django 5.1 on 2024-08-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0015_mess_bank_amount_mess_cash_amount_order_bank_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messtype',
            name='name',
            field=models.CharField(choices=[('breakfast_lunch_dinner', 'Breakfast and Lunch and Dinner'), ('breakfast_lunch', 'Breakfast and Lunch'), ('breakfast_dinner', 'Breakfast and Dinner'), ('lunch_dinner', 'Lunch and Dinner')], max_length=50, unique=True),
        ),
    ]
