# Generated by Django 5.1 on 2024-08-24 15:49

import restaurant_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0017_alter_credituser_time_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DateTimeField(default=restaurant_app.utils.default_time_period),
        ),
    ]
