# Generated by Django 5.1 on 2024-08-25 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0014_alter_credituser_time_period'),
        ('restaurant_app', '0018_alter_credituser_time_period'),
    ]

    operations = [
    ]
