# Generated by Django 5.1 on 2024-08-25 14:49

import restaurant_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0019_merge_20240825_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_newly_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DateTimeField(default=restaurant_app.utils.default_time_period),
        ),
    ]
