# Generated by Django 5.1 on 2024-08-25 20:00

import restaurant_app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0019_merge_20240825_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credituser',
            name='time_period',
            field=models.DateTimeField(default=restaurant_app.utils.default_time_period),
        ),
        migrations.AlterField(
            model_name='user',
            name='passcode',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
