# Generated by Django 5.1 on 2024-08-21 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_drivers', '0002_initial'),
        ('restaurant_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='order_details',
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_order', to='restaurant_app.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverydriver',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverydriver',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
