# Generated by Django 5.1 on 2024-08-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_drivers', '0004_alter_deliveryorder_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverydriver',
            options={'ordering': ('-is_active',)},
        ),
    ]
